### ISSUE TITLE
Change default location in Backup

### ISSUE THREAD

**Issue by PSYQUO** [PSYQUO/SOFENGG#75]

**Comment by EmperorHong** [comment]
where?

**Comment by PSYQUO** [comment]
It was decided that the documents will be placed in the Documents directory of the current user.

**Comment by EmperorHong** [comment]
no default bacccup loccation 
![untitled](https://user-images.githubusercontent.com/25550831/33673339-6b12329a-dae7-11e7-91c6-5e5d223a2e25.png)
